package docfiles_test

import (
	"strings"
	"testing"

	goyze "github.com/gomatic/go-yze"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	docfiles "github.com/gomatic/yze-md-docfiles"
)

// analyze runs the rule over one document, failing the test on a tool error.
func analyze(t *testing.T, at, source string) []goyze.Diagnostic {
	t.Helper()
	diags, err := docfiles.Diagnostics(docfiles.Path(at), docfiles.Source(source))
	require.NoError(t, err)
	return diags
}

// TestAChangelogFileIsReportedInEverySpellingItIsWritten pins the file half of
// the rule, including the canonical Unix spelling with no extension at all.
func TestAChangelogFileIsReportedInEverySpellingItIsWritten(t *testing.T) {
	t.Parallel()

	for _, name := range []string{
		"CHANGELOG.md", "ChangeLog.md", "changelog.markdown", "CHANGE-LOG.txt", "change_log.rst",
		"CHANGES.md", "RELEASE-NOTES.md", "release_notes.adoc", "CHANGELOG", "CHANGELOG.MD",
	} {
		diags := analyze(t, "docs/"+name, "")
		assert.Len(t, diags, 1, "%s is a hand-maintained changelog", name)
	}
}

// TestADocumentThatMerelyMentionsChangelogsIsSilent pins the narrowness that
// keeps the rule usable. Each of these is a real fleet shape, and a rule that
// fired on any of them is one its own repository could not be documented under.
func TestADocumentThatMerelyMentionsChangelogsIsSilent(t *testing.T) {
	t.Parallel()

	for _, name := range []string{
		"changelog-policy.md", "history.md", "notes.md", "changelog.go",
		"CHANGELOG.png", "changelog.md.bak", "my-changes-doc.md",
	} {
		assert.Empty(t, analyze(t, "docs/"+name, ""), "%s is not itself a changelog", name)
	}
}

// TestOnlyProseIsReadForSections pins that the heading half is scoped to prose
// too. An explicitly named source file may hold a markdown fixture in a string
// literal, and reporting that would tell an author their Go file contains a
// changelog.
func TestOnlyProseIsReadForSections(t *testing.T) {
	t.Parallel()

	const embedded = "package x\n\nconst doc = `\n## Changelog\n`\n"

	assert.Empty(t, analyze(t, "fixtures.go", embedded), "code is not prose")
	assert.Len(t, analyze(t, "fixtures.md", embedded), 1, "the same text in prose is a section")
}

// TestGeneratedMarkersExemptADocument pins the ratified scope: the rule is about
// HAND-MAINTAINED prose. A generated document cannot be fixed by editing it, so
// reporting one tells an author to change a file that will be overwritten.
func TestGeneratedMarkersExemptADocument(t *testing.T) {
	t.Parallel()

	for _, marker := range []string{
		"<!-- Code generated by tool. DO NOT EDIT. -->",
		"<!-- @generated -->",
	} {
		assert.Empty(t, analyze(t, "api.md", marker+"\n\n## Changelog\n"), "%s marks generated output", marker)
	}
}

// TestOnlyTheHeaderIsSearchedForAGeneratedMarker pins the other direction, and
// it is the one that matters most here: a document ABOUT the generated-code
// convention says "DO NOT EDIT" in its prose, and exempting on that would let
// any author opt out by writing three words anywhere in the file.
func TestOnlyTheHeaderIsSearchedForAGeneratedMarker(t *testing.T) {
	t.Parallel()

	body := "# Standards\n\nline\nline\nline\nline\n\nGenerated files carry DO NOT EDIT.\n\n## Changelog\n"

	assert.Len(t, analyze(t, "standards.md", body), 1, "a marker below the header exempts nothing")
}

// TestAFileInvitingManualAdditionsIsNotGenerated pins the distinction the fleet
// turns on. Spec-kit writes `MANUAL ADDITIONS` markers into files it expects
// authors to edit, and treating that as a generator's claim would have silently
// excused every finding this rule currently has.
func TestAFileInvitingManualAdditionsIsNotGenerated(t *testing.T) {
	t.Parallel()

	body := "# Project\n\n## Recent Changes\n\n- a thing\n\n<!-- MANUAL ADDITIONS START -->\n"

	assert.Len(t, analyze(t, ".claude/CLAUDE.md", body), 1, "a file authors maintain is hand-maintained")
}

// TestADocumentThatIsNotTextIsAToolFailure pins that a binary file claimed by
// discovery is an error rather than a clean pass. Reading one as prose would
// invent findings from whatever byte happened to look like a `#`.
func TestADocumentThatIsNotTextIsAToolFailure(t *testing.T) {
	t.Parallel()

	_, err := docfiles.Diagnostics("blob.md", docfiles.Source([]byte{0xff, 0xfe, 0x00}))

	require.Error(t, err)
	assert.ErrorIs(t, err, docfiles.ErrNotText)
}

// TestEveryDiagnosticCarriesTheSuiteContract pins the fields the stickler
// consumer reads: without the rule id a finding cannot be softened, baselined
// or attributed, and without a position it cannot be navigated to. The column
// is asserted EXACTLY, not merely as positive — every finding here addresses a
// whole line, so anything but the first column sends a reader to the wrong
// place.
func TestEveryDiagnosticCarriesTheSuiteContract(t *testing.T) {
	t.Parallel()

	diags := analyze(t, "CHANGELOG.md", "## Changelog\n")

	require.Len(t, diags, 2, "the file and its section are separate findings")
	for _, d := range diags {
		assert.Equal(t, "yze", d.Tool)
		assert.Equal(t, docfiles.Rule, d.Rule)
		assert.Equal(t, "CHANGELOG.md", d.Path)
		assert.Equal(t, goyze.SeverityError, d.Severity)
		assert.Positive(t, d.Line)
		assert.Equal(t, 1, d.Col)
		assert.NotEmpty(t, d.Message)
	}
}

// TestAGeneratedChangelogFileIsExemptToo pins that the exemption covers the
// FILE, not only its sections. Exempting only sections reported a
// machine-written CHANGELOG.md as a hand-maintained changelog — recommending
// generated release notes to a file that already was one.
func TestAGeneratedChangelogFileIsExemptToo(t *testing.T) {
	t.Parallel()

	generated := "<!-- Code generated by git-cliff. DO NOT EDIT. -->\n\n## v1.0.0\n"

	assert.Empty(t, analyze(t, "CHANGELOG.md", generated))
	assert.NotEmpty(t, analyze(t, "CHANGELOG.md", "## v1.0.0\n"), "the hand-written one is still reported")
}

// TestGeneratedClaimCannotBeConfusedWithProseQuotingIt pins the marker set. A bare "DO
// NOT EDIT" was a one-line, audit-trail-free opt-out from the whole rule —
// anyone could silence a hand-written changelog by typing three words at the
// top of it — whereas these are the statements a tool writes about its own
// output. Each marker is pinned separately, because one test using a line that
// happens to contain both proves neither.
func TestGeneratedClaimCannotBeConfusedWithProseQuotingIt(t *testing.T) {
	t.Parallel()

	for _, marker := range []string{
		"<!-- Code generated by tool. DO NOT EDIT. -->",
		"<!-- @generated -->",
		"<!-- Code generated by git-cliff. DO NOT EDIT. -->",
	} {
		assert.Empty(t, analyze(t, "notes.md", marker+"\n\n## Changelog\n"), "%s is a generator's claim", marker)
	}

	for _, notAMarker := range []string{
		"<!-- DO NOT EDIT -->",
		"<!-- do not edit -->",
		"<!-- Code generated by tool. -->",
		// The two shapes that wholly exempted real fleet documents: prose
		// QUOTING the convention rather than a generator claiming authorship.
		"Every generated file carries `// Code generated … DO NOT EDIT.` at its top.",
		"Records marked @generated are produced by the planner.",
	} {
		assert.Len(t, analyze(t, "notes.md", notAMarker+"\n\n## Changelog\n"), 1,
			"%s describes the convention rather than claiming authorship", notAMarker)
	}
}

// TestTheGeneratedMarkerIsSearchedToTheEndOfTheHeader pins the boundary in both
// directions: a generator writes its claim at the top, and only the too-large
// direction had a test, so nothing said where the header ends.
func TestTheGeneratedMarkerIsSearchedToTheEndOfTheHeader(t *testing.T) {
	t.Parallel()

	header := "line\nline\nline\nline\n"

	assert.Empty(t, analyze(t, "notes.md", header+"<!-- @generated -->\n\n## Changelog\n"),
		"a marker on the fifth line still exempts")
	assert.Len(t, analyze(t, "notes.md", header+"line\n<!-- @generated -->\n\n## Changelog\n"), 1,
		"one line further down it does not")
}

// TestADocumentTooLargeToBeProseIsAToolFailure pins the read bound. Prose is
// not megabytes, and a file that big is generated output or a mistake — reading
// it costs its own size in memory for a rule that cannot apply.
func TestADocumentTooLargeToBeProseIsAToolFailure(t *testing.T) {
	t.Parallel()

	_, err := docfiles.Diagnostics("huge.md", docfiles.Source(strings.Repeat("x", 9<<20)))

	require.Error(t, err)
	assert.ErrorIs(t, err, docfiles.ErrTooLarge)
}

// TestTruncationNeverLosesTheCountItReplaces pins the bound that replaced unbounded
// accumulation. Streaming the lines moved the amplification into the diagnostic
// slice: eight megabytes of legal prose, every line a banned heading, produced
// 230 MB of report — so a document with this many findings is reported as ONE
// problem, with the true count named rather than silently lost.
func TestTruncationNeverLosesTheCountItReplaces(t *testing.T) {
	t.Parallel()

	flood := strings.Repeat("## Changelog\n", 5000)

	diags := analyze(t, "notes.md", flood)

	require.Len(t, diags, 1001, "the limit, plus the finding that accounts for the rest")
	assert.Contains(t, diags[1000].Message, "5000 changelog findings")
	assert.Contains(t, diags[1000].Message, "1000 are reported")
}

// TestADocumentUnderTheLimitIsReportedInFull pins the other side, so the bound
// never quietly truncates an ordinary document.
func TestADocumentUnderTheLimitIsReportedInFull(t *testing.T) {
	t.Parallel()

	assert.Len(t, analyze(t, "notes.md", strings.Repeat("## Changelog\n", 12)), 12)
}

// TestTheSizeBoundIsExactAtItsEdge pins the boundary itself. A limit is a
// promise about one specific number, and nothing said which side of it the
// limit falls on — so an off-by-one would have been invisible.
func TestTheSizeBoundIsExactAtItsEdge(t *testing.T) {
	t.Parallel()

	atLimit := strings.Repeat("x", int(docfiles.SizeLimit))
	_, err := docfiles.Diagnostics("edge.md", docfiles.Source(atLimit))
	require.NoError(t, err, "a document exactly at the limit is read")

	_, err = docfiles.Diagnostics("edge.md", docfiles.Source(atLimit+"x"))
	require.Error(t, err, "one byte over is not")
	assert.ErrorIs(t, err, docfiles.ErrTooLarge)
}

// TestChangelogFileNameIsUnambiguousInEverySpelling pins the two halves of the vocabulary
// against each other. The heading half admitted a space and the file half did
// not, so `Release Notes.md` — the spelling a person actually types, and the
// package doc's own example of a name that is unambiguous as a FILE — was the
// one shape neither half caught.
func TestChangelogFileNameIsUnambiguousInEverySpelling(t *testing.T) {
	t.Parallel()

	for _, name := range []string{"Change Log.md", "Release Notes.md", "release notes.txt", "CHANGE LOG.md"} {
		assert.Len(t, analyze(t, "docs/"+name, ""), 1, "%s is a changelog by name", name)
	}

	assert.Empty(t, analyze(t, "docs/changelog policy.md", ""), "and a document ABOUT one is still kept")
}

// repeated is a run of one character, for building an underline or a delimiter.
func repeated(of string, times int) string {
	run := ""
	for range times {
		run += of
	}
	return run
}

// TestTheFileFindingNamesTheFileNotItsPath pins what the message says. The path
// is already the diagnostic's own field, so repeating it in the sentence says
// the same thing twice and reads as though a directory were the problem — and
// every assertion checked only a substring both spellings contain.
func TestTheFileFindingNamesTheFileNotItsPath(t *testing.T) {
	t.Parallel()

	diags := analyze(t, "docs/notes/CHANGELOG.md", "")

	require.Len(t, diags, 1)
	assert.Contains(t, diags[0].Message, "CHANGELOG.md is a hand-maintained changelog")
	assert.NotContains(t, diags[0].Message, "docs/notes/CHANGELOG.md is", "the path is the diagnostic's field")
	assert.EqualValues(t, "docs/notes/CHANGELOG.md", diags[0].Path)
}
