package docfiles_test

import (
	"testing"

	goyze "github.com/gomatic/go-yze"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	docfiles "github.com/gomatic/yze-md-docfiles"
)

// analyze runs the rule over one document, failing the test on a tool error.
func analyze(t *testing.T, at, source string) []goyze.Diagnostic {
	t.Helper()
	diags, err := docfiles.Diagnostics(docfiles.Path(at), docfiles.Source(source))
	require.NoError(t, err)
	return diags
}

// TestAChangelogFileIsReportedInEverySpellingItIsWritten pins the file half of
// the rule, including the canonical Unix spelling with no extension at all.
func TestAChangelogFileIsReportedInEverySpellingItIsWritten(t *testing.T) {
	t.Parallel()

	for _, name := range []string{
		"CHANGELOG.md", "ChangeLog.md", "changelog.markdown", "CHANGE-LOG.txt", "change_log.rst",
		"CHANGES.md", "RELEASE-NOTES.md", "release_notes.adoc", "CHANGELOG", "CHANGELOG.MD",
	} {
		diags := analyze(t, "docs/"+name, "")
		assert.Len(t, diags, 1, "%s is a hand-maintained changelog", name)
	}
}

// TestADocumentThatMerelyMentionsChangelogsIsSilent pins the narrowness that
// keeps the rule usable. Each of these is a real fleet shape, and a rule that
// fired on any of them is one its own repository could not be documented under.
func TestADocumentThatMerelyMentionsChangelogsIsSilent(t *testing.T) {
	t.Parallel()

	for _, name := range []string{
		"changelog-policy.md", "history.md", "notes.md", "changelog.go",
		"CHANGELOG.png", "changelog.md.bak", "my-changes-doc.md",
	} {
		assert.Empty(t, analyze(t, "docs/"+name, ""), "%s is not itself a changelog", name)
	}
}

// TestOnlyProseIsReadForSections pins that the heading half is scoped to prose
// too. An explicitly named source file may hold a markdown fixture in a string
// literal, and reporting that would tell an author their Go file contains a
// changelog.
func TestOnlyProseIsReadForSections(t *testing.T) {
	t.Parallel()

	const embedded = "package x\n\nconst doc = `\n## Changelog\n`\n"

	assert.Empty(t, analyze(t, "fixtures.go", embedded), "code is not prose")
	assert.Len(t, analyze(t, "fixtures.md", embedded), 1, "the same text in prose is a section")
}

// TestGeneratedDocumentsAreExempt pins the ratified scope: the rule is about
// HAND-MAINTAINED prose. A generated document cannot be fixed by editing it, so
// reporting one tells an author to change a file that will be overwritten.
func TestGeneratedDocumentsAreExempt(t *testing.T) {
	t.Parallel()

	for _, marker := range []string{
		"<!-- Code generated by tool. DO NOT EDIT. -->",
		"<!-- @generated -->",
	} {
		assert.Empty(t, analyze(t, "api.md", marker+"\n\n## Changelog\n"), "%s marks generated output", marker)
	}
}

// TestOnlyTheHeaderIsSearchedForAGeneratedMarker pins the other direction, and
// it is the one that matters most here: a document ABOUT the generated-code
// convention says "DO NOT EDIT" in its prose, and exempting on that would let
// any author opt out by writing three words anywhere in the file.
func TestOnlyTheHeaderIsSearchedForAGeneratedMarker(t *testing.T) {
	t.Parallel()

	body := "# Standards\n\nline\nline\nline\nline\n\nGenerated files carry DO NOT EDIT.\n\n## Changelog\n"

	assert.Len(t, analyze(t, "standards.md", body), 1, "a marker below the header exempts nothing")
}

// TestAFileInvitingManualAdditionsIsNotGenerated pins the distinction the fleet
// turns on. Spec-kit writes `MANUAL ADDITIONS` markers into files it expects
// authors to edit, and treating that as a generator's claim would have silently
// excused every finding this rule currently has.
func TestAFileInvitingManualAdditionsIsNotGenerated(t *testing.T) {
	t.Parallel()

	body := "# Project\n\n## Recent Changes\n\n- a thing\n\n<!-- MANUAL ADDITIONS START -->\n"

	assert.Len(t, analyze(t, ".claude/CLAUDE.md", body), 1, "a file authors maintain is hand-maintained")
}

// TestADocumentThatIsNotTextIsAToolFailure pins that a binary file claimed by
// discovery is an error rather than a clean pass. Reading one as prose would
// invent findings from whatever byte happened to look like a `#`.
func TestADocumentThatIsNotTextIsAToolFailure(t *testing.T) {
	t.Parallel()

	_, err := docfiles.Diagnostics("blob.md", docfiles.Source([]byte{0xff, 0xfe, 0x00}))

	require.Error(t, err)
	assert.ErrorIs(t, err, docfiles.ErrNotText)
}

// TestEveryDiagnosticCarriesTheSuiteContract pins the fields the stickler
// consumer reads: without the rule id a finding cannot be softened, baselined
// or attributed, and without a position it cannot be navigated to. The column
// is asserted EXACTLY, not merely as positive — every finding here addresses a
// whole line, so anything but the first column sends a reader to the wrong
// place.
func TestEveryDiagnosticCarriesTheSuiteContract(t *testing.T) {
	t.Parallel()

	diags := analyze(t, "CHANGELOG.md", "## Changelog\n")

	require.Len(t, diags, 2, "the file and its section are separate findings")
	for _, d := range diags {
		assert.Equal(t, "yze", d.Tool)
		assert.Equal(t, docfiles.Rule, d.Rule)
		assert.Equal(t, "CHANGELOG.md", d.Path)
		assert.Equal(t, goyze.SeverityError, d.Severity)
		assert.Positive(t, d.Line)
		assert.Equal(t, 1, d.Col)
		assert.NotEmpty(t, d.Message)
	}
}
