package docfiles_test

// The generated-claim exemption, which is the one way out of the HEADING half
// of this rule and so the one place an evasion is worth the most. Every test
// here is a shape that silenced a document by claiming an authorship no
// generator had made.
//
// Every document here is named `api.*` rather than `CHANGELOG.*`. The subject
// is the CLAIM, and a changelog file name produces a finding of its own that no
// claim can suppress — so a table asserting "not exempt" against a
// `CHANGELOG.md` was satisfied by the file finding whether the claim was read
// correctly or not, and measured nothing. The file half has its own test:
// [TestAGeneratedClaimNeverExemptsAChangelogFile].

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestAGeneratedClaimNeverExemptsAChangelogFile pins the half of this rule no
// claim reaches, and it is the half that matters most: the file finding used to
// sit BEHIND the generated check, so a `CHANGELOG.md` opening with
// `Code generated by release-please. DO NOT EDIT.` — which is exactly what
// release-please, git-cliff and goreleaser write — reported NOTHING AT ALL,
// neither the file nor one of its sections. That is the most likely way the ban
// is broken, and the analyzer was blind to precisely it.
//
// Each case asserts BOTH halves at once: exactly one finding, against the file,
// at line 1 — so the file is reported, and the sections of a genuinely generated
// document still are not.
func TestAGeneratedClaimNeverExemptsAChangelogFile(t *testing.T) {
	t.Parallel()

	for name, document := range map[string]struct{ file, source string }{
		"release-please": {
			"CHANGELOG.md",
			"<!-- Code generated by release-please. DO NOT EDIT. -->\n\n## [Unreleased]\n\n## Changelog\n",
		},
		"git-cliff":    {"CHANGELOG.md", "<!-- @generated -->\n\n## Unreleased\n"},
		"restructured": {"CHANGELOG.rst", ".. @generated\n\nChangelog\n=========\n"},
		"asciidoc":     {"CHANGELOG.adoc", "// @generated\n\n== Changelog\n"},
	} {
		diags := analyze(t, document.file, document.source)

		require.Len(t, diags, 1, "%s: the file is reported, and only the file", name)
		assert.Equal(t, 1, diags[0].Line, "%s: the file finding sits at the document's first line", name)
		assert.Contains(t, diags[0].Message, "must not be committed", "%s: and it is the file finding", name)
	}
}

// TestAGeneratedClaimMustBeMadeInTheFormatsOwnComment pins the delimiter per
// FAMILY. It was one list accepted everywhere, so `// @generated` — which
// markdown renders as a visible paragraph reading `// @generated` — exempted a
// hand-written changelog whole. That is the one-line, audit-trail-free opt-out
// this pattern exists to close, reached through a delimiter the format does not
// have.
func TestAGeneratedClaimMustBeMadeInTheFormatsOwnComment(t *testing.T) {
	t.Parallel()

	for name, claim := range map[string]struct {
		file, header string
		exempt       bool
	}{
		"markdown html":       {"api.md", "<!-- @generated -->", true},
		"markdown slashes":    {"api.md", "// @generated", false},
		"markdown block":      {"api.md", "/* @generated */", false},
		"markdown rst":        {"api.md", ".. @generated", false},
		"markdown bare":       {"api.md", "@generated", false},
		"markdown hash":       {"api.md", "# @generated", false},
		"rst comment":         {"api.rst", ".. @generated", true},
		"rst html":            {"api.rst", "<!-- @generated -->", false},
		"asciidoc slashes":    {"api.adoc", "// @generated", true},
		"asciidoc html":       {"api.adoc", "<!-- @generated -->", false},
		"text has no comment": {"api.txt", "<!-- @generated -->", false},
		"text slashes":        {"api.txt", "// @generated", false},
	} {
		found := analyze(t, claim.file, claim.header+"\n\n"+changelogSection(claim.file))

		if claim.exempt {
			assert.Empty(t, found, "%s: a claim in this format's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: text a reader sees is not a generator's claim", name)
	}
}

// TestAMultiLineGeneratedHeaderIsStillAClaim pins the shape a generator actually
// writes, which the block-aware header scan had made invisible: the claim sits
// on its own line BETWEEN `<!--` and `-->`, where the scanner correctly says it
// is not prose — so a genuinely generated document was reported as
// hand-maintained, told to stop maintaining by hand a file nobody edits.
func TestAMultiLineGeneratedHeaderIsStillAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"multi-line":     "<!--\nCode generated by gen-docs. DO NOT EDIT.\n-->",
		"at generated":   "<!--\n@generated\n-->",
		"indented claim": "<!--\n  @generated\n-->",
	} {
		assert.Empty(t, analyze(t, "api.md", header+"\n\n# Changelog\n\n## Unreleased\n"),
			"%s is a generator's claim", name)
	}

	assert.Len(t, analyze(t, "api.md", "<!--\nnotes about generation\n-->\n\n## Changelog\n"), 1,
		"and a comment that merely mentions the subject is not one")
}

// TestAGeneratedClaimInsideAFenceDoesNotExempt pins the same opt-out reached
// through the other door. The header used to be read as raw lines while every
// other reader used the block model, so a document DEMONSTRATING a generated
// header — three lines of an ordinary tutorial — silenced every finding in
// itself.
func TestAGeneratedClaimInsideAFenceDoesNotExempt(t *testing.T) {
	t.Parallel()

	// The claim is written in MARKDOWN's own comment syntax. Shown with `//`,
	// the assertion held whether or not the fence was respected — that delimiter
	// is not a markdown comment at all, so the claim regex rejects it before the
	// block model is ever consulted, and the test named the property without
	// measuring it. Deleting the block-awareness left the suite green.
	fenced := "# Docs\n\n```\n<!-- Code generated by tool. DO NOT EDIT. -->\n```\n\n## Changelog\n"

	assert.Len(t, analyze(t, "api.md", fenced), 1, "the claim is being shown, not made")

	claimed := "<!-- Code generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"
	assert.Empty(t, analyze(t, "api.md", claimed), "and made outside a fence, it really does exempt")
}

// TestAGeneratedClaimIsFoundBehindAByteOrderMark pins that the two readers of a
// document's first line agree. The heading scan stripped the mark and the
// generated-claim scan did not, so a generated file saved by a Windows editor
// had its claim hidden behind an invisible character on exactly the line the
// claim has to be on — and was reported as hand-maintained.
func TestAGeneratedClaimIsFoundBehindAByteOrderMark(t *testing.T) {
	t.Parallel()

	assert.Empty(t, analyze(t, "api.md", "\ufeff<!-- @generated -->\n\n## Changelog\n"))
}

// TestEveryProseExtensionSaysWhetherItHasComments names the generatedClaims
// table and
// pins that the table is complete. A format missing from it is a decision nobody
// wrote down — and the decision is whether one literal line can exempt a
// hand-written changelog from the whole rule.
func TestEveryProseExtensionSaysWhetherItHasComments(t *testing.T) {
	t.Parallel()

	for name, spelling := range map[string]struct {
		file   string
		exempt bool
	}{
		"markdown":      {"api.md", true},
		"markdown long": {"api.markdown", true},
		"restructured":  {"api.rst", true},
		"asciidoc":      {"api.adoc", true},
		"plain text":    {"api.txt", false},
		"extensionless": {"NOTES", false},
	} {
		header := map[bool]string{true: commentedClaim(spelling.file), false: "<!-- @generated -->"}[spelling.exempt]

		found := analyze(t, spelling.file, header+"\n\n"+changelogSection(spelling.file))

		if spelling.exempt {
			assert.Empty(t, found, "%s: a claim in this format's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: this format has no comment, so the claim is text a reader sees", name)
	}
}

// changelogSection is a banned section written the way the file's own format
// spells a heading. One spelling did not serve all three: `## Changelog` opens
// nothing in reStructuredText, whose titles are underlined, so a table row
// asserting the claim did NOT exempt was passing on a document that held no
// section to report in the first place.
func changelogSection(file string) string {
	switch filepath.Ext(file) {
	case ".rst":
		return "Changelog\n=========\n"
	case ".adoc":
		return "== Changelog\n"
	}
	return "## Changelog\n"
}

// commentedClaim is the generated claim written the way the file's own format
// spells a comment.
func commentedClaim(file string) string {
	switch filepath.Ext(file) {
	case ".rst":
		return ".. @generated"
	case ".adoc":
		return "// @generated"
	}
	return "<!-- @generated -->"
}

// TestAClaimIsReadWhereverAComentMayBeIndented pins the indentation a real
// markdown comment tolerates. Up to three spaces is still a comment — CommonMark
// puts a block at four — so a generated header written with a little leading
// space really does exempt, and the trimming that reads it had nothing behind it.
func TestAClaimIsReadWhereverAComentMayBeIndented(t *testing.T) {
	t.Parallel()

	for _, indent := range []string{"", " ", "  ", "   "} {
		assert.Empty(t, analyze(t, "api.md", indent+"<!-- Code generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"),
			"%q of indent is still a comment", indent)
	}

	assert.Len(t, analyze(t, "api.md", "    <!-- Code generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"), 1,
		"four is a code block, and a claim shown in one is not a claim made")
	assert.Len(t, analyze(t, "api.md", "\t<!-- Code generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"), 1,
		"and so is a tab")
}

// TestAClaimOnACommentsClosingLineIsStillAClaim pins the state the claim site is
// read against. A generator writing a multi-line header may put the words on the
// line that CLOSES the comment, and reading that line against the state AFTER it
// — by which point the comment has ended — made it prose that merely mentions
// the words.
func TestAClaimOnACommentsClosingLineIsStillAClaim(t *testing.T) {
	t.Parallel()

	assert.Empty(t, analyze(t, "api.md", "<!--\nCode generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"))
	assert.Empty(t, analyze(t, "api.md", "<!--\nCode generated by tool. DO NOT EDIT.\n-->\n\n## Changelog\n"),
		"and on a line of its own inside the comment")
}

// TestAReStructuredTextDirectiveIsNotAComment pins the difference between RST's
// two `..` forms. A comment vanishes from the rendered page; a directive is a
// visible admonition, so `.. note:: @generated` at the top of a hand-written
// document is a note a reader sees — and it exempted the document whole.
func TestAReStructuredTextDirectiveIsNotAComment(t *testing.T) {
	t.Parallel()

	for _, directive := range []string{".. note:: @generated", ".. warning:: @generated", ".. code::  @generated"} {
		assert.Len(t, analyze(t, "api.rst", directive+"\n\nChangelog\n=========\n"), 1,
			"%q renders, so it declares nothing", directive)
	}

	assert.Empty(t, analyze(t, "api.rst", ".. @generated\n\nChangelog\n=========\n"),
		"while a real comment does declare it")
}
