package docfiles

// The generated-claim exemption: the one way out of the HEADING half of this
// rule, and so the one place an evasion is worth the most.
//
// It is the heading half ALONE. A changelog FILE is banned for existing, and the
// file finding is raised before this check is ever reached — which is what
// closed the hole every generator walked through, since release-please,
// git-cliff and goreleaser all open their `CHANGELOG.md` with a claim. What the
// claim still buys is a machine-written docs page carrying four hundred
// `## Unreleased` headings: that is ONE problem, in its generator, and four
// hundred findings bury it while no author can act on any of them.
//
// The exemption is closed to everything else by asking the PARSER rather than
// the text. A claim counts only inside an HTML comment BLOCK, which is the one
// construct markdown renders as nothing at all — so a document DEMONSTRATING the
// convention, which shows the same words in a fence, in an indented code block
// or in a paragraph, is still judged as the hand-written document it is. Each of
// those was once a one-line, audit-trail-free opt-out from every finding in a
// file, reached through a different door, and each is now a different node.

import (
	"bytes"
	"regexp"

	"github.com/yuin/goldmark/ast"
)

// generatedClaim is the conventional statement a generator makes about its own
// output.
//
// The marker must be a claim of AUTHORSHIP, not merely a request not to edit. A
// bare "DO NOT EDIT" was a three-word opt-out anyone could type at the top of a
// hand-written changelog, and a file that invites manual additions is
// hand-maintained BY DESIGN — while "Code generated … DO NOT EDIT" and
// "@generated" are what tools write about their own output. The trailing period
// is optional and the generator's own words may follow, because that is how they
// actually spell it: gomarkdoc writes `<!-- Code generated by gomarkdoc. DO NOT
// EDIT -->` with no period, and mirror-table writes `<!-- This file is
// @generated by mirror-table, do not edit it manually -->`. Verified against the
// copies in this machine's module cache, not invented.
var generatedClaim = regexp.MustCompile(`Code generated .*DO NOT EDIT|@generated`)

// generatedHeader is how far into a document a claim is looked for. A generator
// writes its claim at the top, and a comment further down is a note about a
// passage rather than a statement about the file — searching the whole document
// exempted two real fleet documents that merely DESCRIBED the convention.
const generatedHeader lineNumber = 5

// isGenerated reports a document that declares itself a generator's output.
//
// Only a TOP-LEVEL block is asked. A comment nested inside a blockquote or a
// list item is a remark about that passage, and a document whose header is a
// quotation is quoting somebody.
func isGenerated(doc document, ext extension) bool {
	if !commentedExtensions[ext] {
		return false
	}
	for child := doc.root.FirstChild(); child != nil; child = child.NextSibling() {
		if doc.declaresGenerated(child) {
			return true
		}
	}
	return false
}

// commentedExtensions says which of the extensions this rule PARSES can carry a
// generated claim at all.
//
// Markdown's only comment is the HTML one, and it renders as nothing. A `.txt`
// or extensionless document is shown to a reader verbatim by every viewer there
// is, so `<!-- @generated -->` in one is a line the reader simply SEES — and
// accepting it there would accept the identical line in a hand-written file,
// which is the one-line, audit-trail-free opt-out this whole file exists to
// close. Both answers are written down: an extension absent from a table is a
// decision nobody made, and this table decides who may silence the rule.
var commentedExtensions = map[extension]bool{
	markdownExt:      true,
	markdownLongExt:  true,
	plainTextExt:     false,
	extensionlessExt: false,
	// MDX has no HTML comment. `<!-- -->` is not valid JSX, so a claim written
	// that way in an `.mdx` file is a syntax error a reader's build shows them
	// rather than an invisible statement of authorship — and accepting it would
	// be accepting a line nobody can hide behind.
	markdownJSXExt: false,
	// The markup spellings are judged by NAME alone and are never parsed, so
	// this question never reaches them. They answer anyway: a table keyed by
	// this type that skipped a member would leave the next reader unable to tell
	// an omission from a decision, which is the failure every table in this
	// package is written against.
	restructuredExt: false,
	asciidocExt:     false,
	asciidocLongExt: false,
}

// declaresGenerated reports one top-level block that IS a generator's claim.
//
// Three things hold together, and each closes a way in: the block is an HTML
// comment (a paragraph saying the same words is text a reader sees), it begins
// within the header (a document quoting the convention halfway down is
// describing it), and the words lie INSIDE the comment's delimiters.
func (d document) declaresGenerated(node ast.Node) bool {
	block, isComment := d.commentBlock(node)
	if !isComment {
		return false
	}
	if d.lineOf(block.Lines().At(0)) > generatedHeader {
		return false
	}
	return generatedClaim.Match(commentInterior(d.commentText(block)))
}

// commentBlock is the node read as an HTML comment, reporting whether it is one.
func (d document) commentBlock(node ast.Node) (*ast.HTMLBlock, bool) {
	block, isHTML := node.(*ast.HTMLBlock)
	if !isHTML || block.Lines().Len() == 0 {
		return nil, false
	}
	return block, invisibleBlocks[block.HTMLBlockType]
}

// invisibleBlocks says which of CommonMark's seven HTML block types render as
// nothing at all. One does; the other six are named here rather than left to a
// comparison — a type absent from the table is a decision nobody wrote down, and
// this table is what stands between an invisible claim and a visible one
// anybody can type.
var invisibleBlocks = map[ast.HTMLBlockType]bool{
	// 2 is the comment, and it is the whole exemption.
	ast.HTMLBlockType2: true,
	// 1 is <script>/<pre>/<style>, 3 is <?…?>, 4 is a <!DECLARATION>, 5 is
	// <![CDATA[…]]>, 6 is a known block tag and 7 any other tag. Each renders
	// as markup a reader sees or as content inside it.
	ast.HTMLBlockType1: false,
	ast.HTMLBlockType3: false,
	ast.HTMLBlockType4: false,
	ast.HTMLBlockType5: false,
	ast.HTMLBlockType6: false,
	ast.HTMLBlockType7: false,
}

// commentText is a comment block's whole text, INCLUDING the line that closes
// it.
//
// Goldmark keeps the closing line in `ClosureLine` rather than in `Lines()`, and
// a generator writing a multi-line header routinely puts the claim there:
// `<!--` on one line and `Code generated by gen-docs. DO NOT EDIT. -->` on the
// next. Reading only `Lines()` reported that genuinely generated document as
// hand-maintained, and told its author to stop editing by hand a file nobody
// edits.
func (d document) commentText(block *ast.HTMLBlock) []byte {
	body := block.Lines().Value(d.source)
	if block.ClosureLine.Start < 0 {
		// An unterminated comment has no closing line; its text is the block.
		return body
	}
	closing := d.textOf(block.ClosureLine)
	whole := make([]byte, 0, len(body)+len(closing))
	return append(append(whole, body...), closing...)
}

// commentInterior is the text BETWEEN a comment's delimiters, which is the only
// part of an HTML comment a reader does not see.
//
// A CommonMark type-2 block ends at the line holding `-->`, and the REST of that
// line belongs to the block — so `<!-- x --> @generated` and
// `<!-- --><span title="@generated">` are both HTML comment blocks carrying the
// words outside the comment, where a reader sees them. Matching the block's
// whole text accepted both, and each was a one-line opt-out from every finding
// in the file.
//
// The opener needs no branch of its own: a type-2 block begins with it by
// definition, and when [bytes.Cut] finds none there is no interior to search.
func commentInterior(text []byte) []byte {
	_, inside, _ := bytes.Cut(text, []byte(commentOpen))
	if closed := bytes.Index(inside, []byte(commentClose)); closed >= 0 {
		return inside[:closed]
	}
	// An unterminated comment runs to the end of the block, and everything in
	// it is still inside the comment.
	return inside
}

// The delimiters of the one construct markdown renders as nothing at all.
const (
	commentOpen  = "<!--"
	commentClose = "-->"
)
