package docfiles_test

// The generated-claim exemption, which is the one way out of the HEADING half
// of this rule and so the one place an evasion is worth the most. Every test
// here is a shape that silenced a document by claiming an authorship no
// generator had made.
//
// Every document here is named `api.*` rather than `CHANGELOG.*`. The subject
// is the CLAIM, and a changelog file name produces a finding of its own that no
// claim can suppress — so a table asserting "not exempt" against a
// `CHANGELOG.md` was satisfied by the file finding whether the claim was read
// correctly or not, and measured nothing. The file half has its own test:
// [TestAGeneratedClaimNeverExemptsAChangelogFile].

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestAGeneratedClaimNeverExemptsAChangelogFile pins the half of this rule no
// claim reaches, and it is the half that matters most: the file finding used to
// sit BEHIND the generated check, so a `CHANGELOG.md` opening with
// `Code generated by release-please. DO NOT EDIT.` — which is exactly what
// release-please, git-cliff and goreleaser write — reported NOTHING AT ALL,
// neither the file nor one of its sections. That is the most likely way the ban
// is broken, and the analyzer was blind to precisely it.
//
// Each case asserts BOTH halves at once: exactly one finding, against the file,
// at line 1 — so the file is reported, and the sections of a genuinely generated
// document still are not. The two markup spellings are here because the file
// half judges those extensions too, and only the file half does.
func TestAGeneratedClaimNeverExemptsAChangelogFile(t *testing.T) {
	t.Parallel()

	for name, document := range map[string]struct{ file, source string }{
		"release-please": {
			"CHANGELOG.md",
			"<!-- Code generated by release-please. DO NOT EDIT. -->\n\n## [Unreleased]\n\n## Changelog\n",
		},
		"git-cliff":    {"CHANGELOG.md", "<!-- @generated -->\n\n## Unreleased\n"},
		"restructured": {"CHANGELOG.rst", ".. @generated\n\nChangelog\n=========\n"},
		"asciidoc":     {"CHANGELOG.adoc", "// @generated\n\n== Changelog\n"},
	} {
		diags := analyze(t, document.file, document.source)

		require.Len(t, diags, 1, "%s: the file is reported, and only the file", name)
		assert.Equal(t, 1, diags[0].Line, "%s: the file finding sits at the document's first line", name)
		assert.Contains(t, diags[0].Message, "must not be committed", "%s: and it is the file finding", name)
	}
}

// TestAGeneratedClaimMustBeMadeInMarkdownsOwnComment pins the delimiter. Only
// the HTML comment vanishes from a rendered page; every other spelling of the
// claim is a line a reader plainly SEES, and accepting one let `// @generated`
// — which markdown renders as a visible paragraph reading `// @generated` —
// exempt a hand-written changelog whole. That is the one-line,
// audit-trail-free opt-out this check exists to close, reached through a
// delimiter the format does not have.
func TestAGeneratedClaimMustBeMadeInMarkdownsOwnComment(t *testing.T) {
	t.Parallel()

	for name, claim := range map[string]struct {
		header string
		exempt bool
	}{
		"html comment":     {"<!-- @generated -->", true},
		"c line comment":   {"// @generated", false},
		"c block comment":  {"/* @generated */", false},
		"rst comment":      {".. @generated", false},
		"bare words":       {"@generated", false},
		"hash comment":     {"# @generated", false},
		"list item":        {"- @generated", false},
		"blockquoted":      {"> <!-- @generated -->", false},
		"do not edit only": {"<!-- DO NOT EDIT -->", false},
		"lower case":       {"<!-- do not edit -->", false},
		"generated only":   {"<!-- Code generated by tool. -->", false},
	} {
		found := analyze(t, "api.md", claim.header+"\n\n## Changelog\n")

		if claim.exempt {
			assert.Empty(t, found, "%s: a claim in markdown's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: text a reader sees is not a generator's claim", name)
	}
}

// TestAClaimIsProseWhereverAFormatHasNoComment pins the two extensions this
// rule parses as markdown while nothing renders them as markdown. A `.txt` or
// extensionless document is shown to a reader verbatim, so `<!-- @generated -->`
// in one is a line the reader sees — and accepting it there accepts the
// identical line in a hand-written file.
func TestAClaimIsProseWhereverAFormatHasNoComment(t *testing.T) {
	t.Parallel()

	for name, spelling := range map[string]struct {
		file   string
		exempt bool
	}{
		"markdown":      {"api.md", true},
		"markdown long": {"api.markdown", true},
		"plain text":    {"api.txt", false},
		"extensionless": {"NOTES", false},
	} {
		found := analyze(t, spelling.file, "<!-- @generated -->\n\n## Changelog\n")

		if spelling.exempt {
			assert.Empty(t, found, "%s: a claim in this format's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: this format has no comment, so the claim is text a reader sees", name)
	}
}

// TestAMultiLineGeneratedHeaderIsStillAClaim pins the shape a generator actually
// writes: the claim sits on its own line BETWEEN `<!--` and `-->`, and a check
// that read only the first line reported a genuinely generated document as
// hand-maintained — telling its author to stop maintaining by hand a file
// nobody edits.
func TestAMultiLineGeneratedHeaderIsStillAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"multi-line":     "<!--\nCode generated by gen-docs. DO NOT EDIT.\n-->",
		"at generated":   "<!--\n@generated\n-->",
		"indented claim": "<!--\n  @generated\n-->",
		"unterminated":   "<!--\n@generated",
	} {
		assert.Empty(t, analyze(t, "api.md", header+"\n\n# Changelog\n\n## Unreleased\n"),
			"%s is a generator's claim", name)
	}

	assert.Len(t, analyze(t, "api.md", "<!--\nnotes about generation\n-->\n\n## Changelog\n"), 1,
		"and a comment that merely mentions the subject is not one")
}

// TestAClaimOnACommentsClosingLineIsStillAClaim pins the line goldmark keeps
// apart from the rest of the block. A comment's closing line is its
// `ClosureLine` rather than one of its `Lines`, and a generator writing
// `<!--` / `Code generated … DO NOT EDIT. -->` puts the whole claim there — so
// reading only the block's lines misses the commonest multi-line header there
// is.
func TestAClaimOnACommentsClosingLineIsStillAClaim(t *testing.T) {
	t.Parallel()

	assert.Empty(t, analyze(t, "api.md", "<!--\nCode generated by tool. DO NOT EDIT. -->\n\n## Changelog\n"))
	assert.Empty(t, analyze(t, "api.md", "<!--\nCode generated by tool. DO NOT EDIT.\n-->\n\n## Changelog\n"),
		"and on a line of its own inside the comment")
}

// TestWordsOutsideTheCommentOnItsOwnLineAreNotAClaim pins the boundary the
// block's extent hides. A type-2 HTML block ends at the line holding `-->`, and
// the REST of that line belongs to the block while a reader plainly sees it —
// so matching the block's whole text accepted `<!-- x --> @generated`, which
// renders the words as visible prose. Each is a one-line opt-out from every
// finding in the file.
func TestWordsOutsideTheCommentOnItsOwnLineAreNotAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"after the closer":   "<!-- x --> @generated",
		"in a tag attribute": `<!-- --><span title="@generated">`,
	} {
		assert.Len(t, analyze(t, "api.md", header+"\n\n## Changelog\n"), 1,
			"%s: the words are outside the comment, where a reader sees them", name)
	}
}

// TestAGeneratedClaimIsShownRatherThanMadeInsideABlock pins the same opt-out
// reached through the doors a document opens when it DESCRIBES the convention.
// Three lines of an ordinary tutorial once silenced every finding in the file
// that held them.
func TestAGeneratedClaimIsShownRatherThanMadeInsideABlock(t *testing.T) {
	t.Parallel()

	const claim = "<!-- Code generated by tool. DO NOT EDIT. -->"

	for name, source := range map[string]string{
		"fenced":        "# Docs\n\n```\n" + claim + "\n```\n\n## Changelog\n",
		"indented code": "    " + claim + "\n\n## Changelog\n",
		"tab code":      "\t" + claim + "\n\n## Changelog\n",
	} {
		assert.Len(t, analyze(t, "api.md", source), 1, "%s: the claim is being shown, not made", name)
	}

	assert.Empty(t, analyze(t, "api.md", claim+"\n\n## Changelog\n"),
		"and made at the margin, it really does exempt")

	for _, indent := range []string{" ", "  ", "   "} {
		assert.Empty(t, analyze(t, "api.md", indent+claim+"\n\n## Changelog\n"),
			"%q of indent is still a comment rather than code", indent)
	}
}
