package docfiles_test

// The generated-file exemption, which is the one way out of this rule and so
// the one place an evasion is worth the most. Every test here is a shape that
// silenced a whole document by claiming an authorship no generator had made.

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestAGeneratedClaimMustBeMadeInTheFormatsOwnComment pins the delimiter per
// FAMILY. It was one list accepted everywhere, so `// @generated` — which
// markdown renders as a visible paragraph reading `// @generated` — exempted a
// hand-written changelog whole. That is the one-line, audit-trail-free opt-out
// this pattern exists to close, reached through a delimiter the format does not
// have.
func TestAGeneratedClaimMustBeMadeInTheFormatsOwnComment(t *testing.T) {
	t.Parallel()

	for name, claim := range map[string]struct {
		file, header string
		exempt       bool
	}{
		"markdown html":       {"CHANGELOG.md", "<!-- @generated -->", true},
		"markdown slashes":    {"CHANGELOG.md", "// @generated", false},
		"markdown block":      {"CHANGELOG.md", "/* @generated */", false},
		"markdown rst":        {"CHANGELOG.md", ".. @generated", false},
		"markdown bare":       {"CHANGELOG.md", "@generated", false},
		"markdown hash":       {"CHANGELOG.md", "# @generated", false},
		"rst comment":         {"CHANGELOG.rst", ".. @generated", true},
		"rst html":            {"CHANGELOG.rst", "<!-- @generated -->", false},
		"asciidoc slashes":    {"CHANGELOG.adoc", "// @generated", true},
		"asciidoc html":       {"CHANGELOG.adoc", "<!-- @generated -->", false},
		"text has no comment": {"CHANGELOG.txt", "<!-- @generated -->", false},
		"text slashes":        {"CHANGELOG.txt", "// @generated", false},
	} {
		found := analyze(t, claim.file, claim.header+"\n\n## Changelog\n")

		if claim.exempt {
			assert.Empty(t, found, "%s: a claim in this format's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: text a reader sees is not a generator's claim", name)
	}
}

// TestAMultiLineGeneratedHeaderIsStillAClaim pins the shape a generator actually
// writes, which the block-aware header scan had made invisible: the claim sits
// on its own line BETWEEN `<!--` and `-->`, where the scanner correctly says it
// is not prose — so a genuinely generated document was reported as
// hand-maintained, told to stop maintaining by hand a file nobody edits.
func TestAMultiLineGeneratedHeaderIsStillAClaim(t *testing.T) {
	t.Parallel()

	for name, header := range map[string]string{
		"multi-line":     "<!--\nCode generated by gen-docs. DO NOT EDIT.\n-->",
		"at generated":   "<!--\n@generated\n-->",
		"indented claim": "<!--\n  @generated\n-->",
	} {
		assert.Empty(t, analyze(t, "api.md", header+"\n\n# Changelog\n\n## Unreleased\n"),
			"%s is a generator's claim", name)
	}

	assert.Len(t, analyze(t, "api.md", "<!--\nnotes about generation\n-->\n\n## Changelog\n"), 1,
		"and a comment that merely mentions the subject is not one")
}

// TestAGeneratedClaimInsideAFenceDoesNotExempt pins the same opt-out reached
// through the other door. The header used to be read as raw lines while every
// other reader used the block model, so a document DEMONSTRATING a generated
// header — three lines of an ordinary tutorial — silenced every finding in
// itself.
func TestAGeneratedClaimInsideAFenceDoesNotExempt(t *testing.T) {
	t.Parallel()

	fenced := "# Docs\n\n```go\n// Code generated by mockgen. DO NOT EDIT.\n```\n\n## Changelog\n"

	assert.Len(t, analyze(t, "api.md", fenced), 1, "the claim is being shown, not made")
}

// TestAGeneratedClaimIsFoundBehindAByteOrderMark pins that the two readers of a
// document's first line agree. The heading scan stripped the mark and the
// generated-claim scan did not, so a generated file saved by a Windows editor
// had its claim hidden behind an invisible character on exactly the line the
// claim has to be on — and was reported as hand-maintained.
func TestAGeneratedClaimIsFoundBehindAByteOrderMark(t *testing.T) {
	t.Parallel()

	assert.Empty(t, analyze(t, "api.md", "\ufeff<!-- @generated -->\n\n## Changelog\n"))
}

// TestEveryProseExtensionSaysWhetherItHasComments names the generatedClaims
// table and
// pins that the table is complete. A format missing from it is a decision nobody
// wrote down — and the decision is whether one literal line can exempt a
// hand-written changelog from the whole rule.
func TestEveryProseExtensionSaysWhetherItHasComments(t *testing.T) {
	t.Parallel()

	for name, spelling := range map[string]struct {
		file   string
		exempt bool
	}{
		"markdown":      {"CHANGELOG.md", true},
		"markdown long": {"CHANGELOG.markdown", true},
		"restructured":  {"CHANGELOG.rst", true},
		"asciidoc":      {"CHANGELOG.adoc", true},
		"plain text":    {"CHANGELOG.txt", false},
		"extensionless": {"CHANGELOG", false},
	} {
		header := map[bool]string{true: commentedClaim(spelling.file), false: "<!-- @generated -->"}[spelling.exempt]

		found := analyze(t, spelling.file, header+"\n\n## Changelog\n")

		if spelling.exempt {
			assert.Empty(t, found, "%s: a claim in this format's own comment", name)
			continue
		}
		assert.NotEmpty(t, found, "%s: this format has no comment, so the claim is text a reader sees", name)
	}
}

// commentedClaim is the generated claim written the way the file's own format
// spells a comment.
func commentedClaim(file string) string {
	switch filepath.Ext(file) {
	case ".rst":
		return ".. @generated"
	case ".adoc":
		return "// @generated"
	}
	return "<!-- @generated -->"
}
